### ISSUE TITLE
Issue with .toUpperCase()

### ISSUE THREAD

**Issue by ziyafenn** [ajwhite/render-if#16]
Hi there! Thanks a lot for this great function, saves a lot of time!

Only issue though!

In this example:
```
{renderIf(heading)(
		<Title label={heading.toUpperCase()} /> 
		)}
```

I will get an error **Undefined is not an object(evaluating 'heading.toUpperCase')** if i leave the `heading` prop empty (or just not use it all) when i render it somewhere else, even though it should not be rendered at all! 

Any way to fix it? 

Thanks!

**Comment by atticoos** [comment]
This will still _evaluate_ the expression since it's all synchronous. You'll want to use [lazy evaluation](https://github.com/ajwhite/render-if#as-a-lazy-in-line-expression) here to _defer evaluation_ until the predicate passes.

```js
{renderIf(heading)(() => (
  <Title label={heading.toUpperCase()} />
))
```

By wrapping it in a function, it doesn't become evaluated until the function is called. And the function does not become called unless the predicate passes.

That should do it!
